# Generated by Django 5.2 on 2025-05-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_completed',
        ),
    ]
